### ISSUE TITLE
Stripe custom button

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/open-eshop#125]
https://gist.github.com/andrewpthorp/8342935

**Comment by neo22s** [comment]
also for OC ;)

**Comment by neo22s** [comment]
esta en OC? sino para 2.5.0

**Comment by oliverds** [comment]
Sí lo está, commit en [BB](https://bitbucket.org/neo22s/open-classifieds-private/commits/505d49fd62faeffc032f2fb1a1dcfd4adba5b522).
