### ISSUE TITLE
"Can be downloaded x times" in product e-mail

### ISSUE THREAD

**Issue by kinanhamwi** [open-classifieds/open-eshop#392]
Right now when you create a product or a service and when you make a sale the client receives an e-mail that has the product notes and at the end there is the line "can be downloaded x times" x depends on the number of times to download.

This doesn't apply on services and the line shouldn't be mentioned on services (or anything that doesn't require a download)

Suggested fix: apply download restrictions depending on category

**Comment by neo22s** [comment]
Much easier, if theres no file attached should not appear ;) thats the error actually.
