### ISSUE TITLE
Error while sending mail throught smtp

### ISSUE THREAD

**Issue by g4m3r0** [open-classifieds/open-eshop#404]
I get this error since I updated to 1.8 while sending an email via smtp.
E.g. Remember Password, Registration etc. 

Tested with different smtp mail servers, sending mails (port) isn't blocked on my vps.

This Warning appears after reaching the timeout:
Warning
Mailer Error: SMTP connect() failed.

This error was logged:
2015-04-10 07:07:00 --- ERROR: ErrorException [ 2 ]: Error while sending QUERY packet. PID=992 ~ APPPATH/common/modules/mysqli/classes/kohana/database/mysqli.php [ 174 ] in /home/admin/web/shop.gsoftwarelab.com/public_html/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110

**Comment by neo22s** [comment]
That is a SMTP error. Verify your SMTP config in the APP and in the server side.

The error in the log is a problem on server side. The connection to mysql was lost.

Before opening an issue on github please read: https://github.com/open-classifieds/open-eshop/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by g4m3r0** [comment]
First I verified my SMTP Server.
Second I used another SMTP Server.
Finally I verified my mysql server it was stable and running the whole time when the error appeared.

This error appeared first after upgrading to 1.8 so I think that this is the reason, or?
