### ISSUE TITLE
License check api

### ISSUE THREAD

**Issue by phoomin2012** [open-classifieds/open-eshop#427]
How to coding to check license in server side?

**Comment by neo22s** [comment]
pretty simple ;)

http://yourdomain.com/api/license/HERETHELICENSENUMBER/?domain=theclientdomain.com

The parameter domain= its not mandatory. In case you do not send it the software tries to resolve it.

The API returns a json with TRUE or FALSE. True is the license is valid for ht domain and not out of date, false when not good.

thats all ;)

Please next time check this https://github.com/open-classifieds/open-eshop/blob/master/CONTRIBUTING.md#reporting-issues
