### ISSUE TITLE
Needs an automatic Updater

### ISSUE THREAD

**Issue by dodiaraculus17** [open-classifieds/open-eshop#439]
I noticed that when the system updates you have to use patches instead you should use something like this:
http://maxmorgandesign.com/simple_php_auto_update_system/

**Comment by neo22s** [comment]
Can you please elaborate?

what you mean patches? to update the db?

Yeah automatic updates could be done better I guess not the nicest code, but since last modifications seems to be working pretty fine.

I have checked the code, what we have is a bit more complex since deals with DB updates and only updates files that have been changed.

What we could do for sure is improve our updater. to make it work more smoothly, love how works at wordpress....maybe we should just go and copy it ;)

thanks.

**Comment by dodiaraculus17** [comment]
So I have used this is my script it allows you to automatically update the database and also update the files and folders. To do this you need an update server with a lot of store. I will allow you to use mine, the server will need to store zip files and one file that has the current version. On the client end we will need to add an updater which will extract the zip file and automatically copy, delete, and move files.

**Comment by neo22s** [comment]
We have something really similar but files hosted on github much better ;)

**Comment by dodiaraculus17** [comment]
Great

**Comment by dodiaraculus17** [comment]
So I am willing to program this and add it. Do you want it.

**Comment by dodiaraculus17** [comment]
OK In order to build this we will need to use something like C9.IO or do you have anything like this.

**Comment by neo22s** [comment]
of course!! that would be great, lets discuss how will exactly will work.

First we need to analyze what we have currently so its compatible with old versions and they are able to update.

Please check this files:
https://github.com/open-classifieds/open-eshop/blob/master/oc/classes/controller/panel/update.php
https://github.com/open-classifieds/common/blob/master/classes/controller/panel/oc/update.php

We have vagrant and docker images https://github.com/open-classifieds/docker https://github.com/open-classifieds/vagrant

**Comment by dodiaraculus17** [comment]
So do you have a C9.IO account or can you create one, then I will tell you my email.

**Comment by dodiaraculus17** [comment]
https://ide.c9.io/dodiaraculus/open-eshop is the link to the development console.

**Comment by dodiaraculus17** [comment]
Here is the plan I will have it automatically pull files on the installer

**Comment by dodiaraculus17** [comment]
//Copy code
function recurse_copy($src,$dst) { 
    $dir = opendir($src); 
    @mkdir($dst); 
    while(false !== ( $file = readdir($dir)) ) { 
        if (( $file != '.' ) && ( $file != '..' )) { 
            if ( is_dir($src . '/' . $file) ) { 
                recurse_copy($src . '/' . $file,$dst . '/' . $file); 
            } 
            else { 
                copy($src . '/' . $file,$dst . '/' . $file); 
            } 
        } 
    } 
    closedir($dir); 
} 
//delete update folder
public static function deleteDir($dirPath) {
    if (! is_dir($dirPath)) {
        throw new InvalidArgumentException("$dirPath must be a directory");
    }
    if (substr($dirPath, strlen($dirPath) - 1, 1) != '/') {
        $dirPath .= '/';
    }
    $files = glob($dirPath . '*', GLOB_MARK);
    foreach ($files as $file) {
        if (is_dir($file)) {
            self::deleteDir($file);
        } else {
            unlink($file);
        }
    }
    rmdir($dirPath);
}
function oninstall_updater() {
 //get the update files off of github
 $github_location = "[LINK_TO_PROJECT]";
 //Make the directory updates
 mkdir("updates");
 //Get the updates off of url
 $contents_of_zip = file_get_contents($github_location);
 //Save the files to updates/updates.zip
 file_put_contents("updates/updates.zip", $contents_of_zip);
 //Extract the zip
 system("unzip updates/updates.zip");
 //Copy all files for overwritting files
 recurse_copy("open-eshop-master/","/");
 
 deleteDir("updates");
}

**Comment by neo22s** [comment]
We develop on local and then you can do a pull request is that simple ;)

**Comment by dodiaraculus17** [comment]
It will not let me publish because I need to be part of the project can you invite me.

**Comment by neo22s** [comment]
Hello,

What you need to do is to clone the project, then work on your cloned project and do a pull request to the original, is the normal workflow and how all the collaborators do ;)

**Comment by dodiaraculus17** [comment]
Mine is not working it says I don't have permission to do a pull request.

**Comment by neo22s** [comment]
You need to do it form here:
https://github.com/dodiaraculus17/open-eshop

Anyone can do a PR. You need to commit your changes to https://github.com/dodiaraculus17/open-eshop and once you are done then do a PR, you can do it form github directly. https://help.github.com/articles/using-pull-requests/ and our contribution file as example read from here: https://github.com/open-classifieds/openclassifieds2/blob/master/CONTRIBUTING.md#how-to-commit

**Comment by dodiaraculus17** [comment]
Thanks BTW Awesome System. Can I have a full version copy

**Comment by neo22s** [comment]
welcome!! sure you can pull it following the instructions you need common and eshop ;)

**Comment by dodiaraculus17** [comment]
Here is what I got so far, what do you think:
function pullfilesfrominternet() {
 	try
 	{
 		$pull_url = "[github_url]";
 		if (is_writable("update.zip"))
 		{
 			if (file_get_contents($pull_url) != "")
 			{
 				//Able to get file with write permissions
 			file_put_contents("update.zip",file_get_contents($pull_url));
 			system("unzip update.zip") or echo "Cannot Extract Files [Skipping this step]";
 			unlink("update.zip") or echo "Cannot Extract Files [Skipping this Step]";
 			//Successfully downloaded files and
 			} else {
 				echo "Cannot Connect to " . $pull_url . "[Skipping this Step]";
 			}
 			
 		} else {
 			echo "Requires Write Permission[Skipping this Step]";
 		}
 	} catch (exception $e) {}
 }

**Comment by neo22s** [comment]
system("unzip update.zip")  ? that won't work in many hosting ;)

Please before moving forward read about our coding standards so later we can reuse the code http://kohanaframework.org/3.3/guide/kohana/conventions

**Comment by dodiaraculus17** [comment]
How about this
```
function pullfilesfrominternet() {
 	try
 	{
 		$pull_url = "[github_url]";
 		if (is_writable("update.zip"))
 		{
 			if (file_get_contents($pull_url) != "")
 			{
 				//Able to get file with write permissions
 			file_put_contents("update.zip",file_get_contents($pull_url));
 			//system("unzip update.zip");
 			$zip = new ZipArchive;
if ($zip->open('update.zip') === TRUE) {
  $zip->extractTo('');
  $zip->close();
  echo 'ok';
} else {
  echo 'failed';
}
 			unlink("update.zip") or echo "Cannot Extract Files [Skipping this Step]";
 			//Successfully downloaded files and deleted zip file
 			//Time for some magic ;)
 			//Register the recuse_copy
 			 function recurse_copy($src,$dst) { 
        $dir = opendir($src); 
        @mkdir($dst); 
        while(false !== ( $file = readdir($dir)) ) { 
            if (( $file != '.' ) && ( $file != '..' )) { 
                if ( is_dir($src . '/' . $file) ) { 
                    recurse_copy($src . '/' . $file,$dst . '/' . $file); 
                } 
                else { 
                    copy($src . '/' . $file,$dst . '/' . $file); 
                } 
            } 
        } 
        closedir($dir); 
    } 
    //Move all the files 
    recurse_copy("open-eshop-master","/");
 			} else {
 				echo "Cannot Connect to " . $pull_url . "[Skipping this Step]";
 			}
 			
 		} else {
 			echo "Requires Write Permission[Skipping this Step]";
 		}
 	} catch (exception $e) {}
 }
```

**Comment by dodiaraculus17** [comment]
https://github.com/open-classifieds/open-eshop/compare/master...dodiaraculus17:patch-5

**Comment by dodiaraculus17** [comment]
How can I publish this.

**Comment by neo22s** [comment]
can not merge this, it doesnt follow our coding standards and duplicates functionality we already have like recurse_copy also it is defined inside a function :o:

Sorry I will not merge anything which doesnt follow all the other code style and best practices.

Also avoid duplicated code.

see:
http://kohanaframework.org/3.3/guide/kohana/conventions

And our current update system:
https://github.com/open-classifieds/open-eshop/blob/master/oc/classes/controller/panel/update.php
https://github.com/open-classifieds/common/blob/master/classes/controller/panel/oc/update.php

It seems does the same as what you want to do but better actually :s

I am not sure what kind of improvement you want to add but what I have seen so far doesn't look like something we need.

I really appreciate the effort and your time I am thankful to any contribution but we need to be sure a minimum quality stands to our thousands of users.

thanks

**Comment by dodiaraculus17** [comment]
:-1:

**Comment by neo22s** [comment]
I am sorry you get disappointed, I hope you understand I do not mind explaining to you and showing you the path at all, I love to help ;)

But we need to have clear the path and follow our internals if not this is chaos ;)

**Comment by dodiaraculus17** [comment]
What is the problem exactly with my code I don't understand

**Comment by dodiaraculus17** [comment]
So what was the function for recurse_copy

**Comment by dodiaraculus17** [comment]
Here ya go http://collabedit.com/n98g5

**Comment by neo22s** [comment]
1 - theres a function defined inside a function
2 - theres a function which already exists on our code base. file::copy
3 - Coding standard is not respected at all
4 - usage of echo instead of outputing the results
5 - function is outside the controller :s
6 - PR should finish an entire task/issue, if not can not be merged since can not go to production.

**Comment by dodiaraculus17** [comment]
Ok so did you use the link

**Comment by neo22s** [comment]
Before developing any further, what is exactly that you do not like from our current process and how do you intend to improve it? which suggestions you have? what solutions you propose?

Once we have that clear then we can code, never before ;)

**Comment by dodiaraculus17** [comment]
The system does not automatically update and I want to make a automatic update that updates files, folders, and the database.

**Comment by neo22s** [comment]
All that you are describing its already developed :S

Please read this class and the comments:
https://github.com/open-classifieds/common/blob/master/classes/controller/panel/oc/update.php#L124

What is exactly not working?

**Comment by dodiaraculus17** [comment]
I am making it more simple I noticed that I could shorten the code down because you don't need all of that there is a more simple method I will be glad to show you. ; )

**Comment by neo22s** [comment]
I am more than happy then! any improvement is welcome.

Please describe in detail the new process and whats wrong in current one (sure plenty of stuff), once we agree then you can start coding it, then once its done and all working you can do a PR.

thanks

**Comment by dodiaraculus17** [comment]
Can I show you?

**Comment by dodiaraculus17** [comment]
Here is the link again. http://collabedit.com/n98g5

**Comment by neo22s** [comment]
that code has many of the issues detailed before.

Please to contribute once more:
1-respect coding standard
2-detail work you want to do
3-do PR of work completed

Thanks

**Comment by dodiaraculus17** [comment]
Can you help me with it

**Comment by neo22s** [comment]
Then I will code it, no?

Before ever coding I need to have an exact idea of what I am going to code, I am still waiting for the new better process.

For me at least its impossible to code without knowing what I want first.

Going to sleep 11:30pm here at 7am working again. Please follow instructions and read our docs.

thanks

**Comment by dodiaraculus17** [comment]
Ok just visit http://collabedit.com/n98g5 and I will explain further.
