### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/open-eshop#448]
docs.open-eshop.com using HTTPS. gh-pages this same domain.

**Comment by kotsios5** [comment]
work on http://kotsios5.github.io/open-eshop-documentation

**Comment by neo22s** [comment]
@kotsios5 how do you see this?

**Comment by kotsios5** [comment]
It only needs to create any guides are missing, if there are any. Then to push it on the original repo (that will use docs.open-eshop.com) and I think it's ready. 

It could be done this week.

**Comment by neo22s** [comment]
cool! also include the links inside the panel

Like we have for oc, each section the link to the proper guide. take your time ;)

**Comment by kotsios5** [comment]
I think it's done: http://kotsios5.github.io/open-eshop-documentation

We can push it to docs.open-eshop.com so I can include the links in the panel.

**Comment by neo22s** [comment]
ok, sure! add it here:
https://github.com/open-classifieds/documentation-oe

Then add a file like this one:
https://github.com/open-classifieds/documentation/blob/gh-pages/CNAME
with content docs.open-eshop.com

**Comment by kotsios5** [comment]
I need to fork before pushing and I can't fork because it's empty.

**Comment by neo22s** [comment]
ups! ready!
