### ISSUE TITLE
Improve modal look and feel.

### ISSUE THREAD

**Issue by neo22s** [open-classifieds/open-eshop#450]
Could not be any uglier....

![image](https://cloud.githubusercontent.com/assets/241725/11569300/7adb8ca0-99f1-11e5-9cb2-b3ee806583ee.png)

**Comment by oliverds** [comment]
Could be worse haha but yeah it doesn't look good. Guess the visual problem is because it has two different background colors.

Not really sure how this modal content is loaded.

**Comment by neo22s** [comment]
we use:
https://github.com/open-classifieds/open-eshop/blob/master/themes/default/views/main-minimal.php
and loaded from
https://github.com/open-classifieds/open-eshop/blob/master/embed.js
