### ISSUE TITLE
Message after installation

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/open-eshop#465]
Every time I do a clean installation, after the installation finishes i choose to go to admin panel and this text appears:

![install-oe](https://cloud.githubusercontent.com/assets/11571490/11976021/e12ca35c-a96b-11e5-8e72-705314f364a9.png)

**Comment by neo22s** [comment]
only once, correct? thats cuz sitemap file is missing or doesnt have permissions. I will take a look, thanks

**Comment by kotsios5** [comment]
yes, only once!

**Comment by neo22s** [comment]
now is identicall to OC so should work, you can try ;)

**Comment by kotsios5** [comment]
Yeap! The message is not appearing now!
