### ISSUE TITLE
Add support for Avangate payment gateway

### ISSUE THREAD

**Issue by themestrap93** [open-classifieds/open-eshop#484]

**Comment by neo22s** [comment]
Can you implement it?

**Comment by themestrap93** [comment]
No I am not a developer but can provide the documentation if need be.

**Comment by neo22s** [comment]
Please use the suggestion forum if you are not a developer and if you get enough supporters we will consider the development https://market.open-eshop.com/forum/suggestions

You can always sponsor the development.

regards and thanks
