### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by kotsios5** [open-classifieds/open-eshop#525]
https://market.open-eshop.com/forum/support/some-optical-errors.html
https://market.open-eshop.com/forum/suggestions/irritating-checkbox.html

**Comment by g4m3r0** [comment]
I found another design issue in version 2.6 on the page & email edit page.
![2016-11-17 22_36_51-edit](https://cloud.githubusercontent.com/assets/9322695/20408566/5955439e-ad16-11e6-9e6b-61b4b5d77a68.png)

**Comment by neo22s** [comment]
Whats your domain name? Not happening to me please check your php version
