### ISSUE TITLE
Products are invisible on Panel Index

### ISSUE THREAD

**Issue by g4m3r0** [open-classifieds/open-eshop#532]
Since I updated to version 2.6 my products on the panel index are not listed anymore.

![2016-11-17 23_04_38-product - gsoftwarelab shop](https://cloud.githubusercontent.com/assets/9322695/20409558/64102552-ad1a-11e6-81aa-27586a029e05.png)

They still exist in the DB and I can access them via /oc-panel/Product/update/PRODUCT_ID .

Regards

**Comment by neo22s** [comment]
Whats your domain name? Not happening to me please check your php version

**Comment by g4m3r0** [comment]
https://shop.gsoftwarelab.com I use PHP Version 7.0.10

**Comment by neo22s** [comment]
Inspect with chrome you must have an error there. Or check in log errors
what it says?

Just checked in 3sites all of them working good

**Comment by g4m3r0** [comment]
You are right it seems to be cause by cloudflare mintify/rocketloader.
However the last version worked.

![2016-11-17 23_20_13- 1 products are invisible on panel index issue 532 open-classifieds_open-e](https://cloud.githubusercontent.com/assets/9322695/20410253/6f102306-ad1c-11e6-92ef-fccf50ace61f.png)
