### ISSUE TITLE
Will moved to home after adding coupon

### ISSUE THREAD

**Issue by g4m3r0** [open-classifieds/open-eshop#533]
If I add a coupon on the product page and press the add button I will be moved to the home page of the shop.

**Comment by neo22s** [comment]
you mean redirected no? ;) ok we will review.

Can you please make a video or technical.

Version, Browser, Theme and URL so we can test.

**Comment by g4m3r0** [comment]
Yes I mean redirected :).

OE version is 2.6
Tested with Chrome and IE
Url is: https://shop.gsoftwarelab.com

This issue is also on free products. If I press the free download button -> regsiter a new account -> redirected to shop's home.

If I enter a coupon on product page -> redirected to shop's home (coupon will be applied)
